### ISSUE TITLE
Missing endpoint input files

### ISSUE THREAD

**Issue by ycfhw1** [CN-UPB/FutureCoord#1]
hello,where is the endpoints file .npy in experiments except abilene?

**Comment by stefanbschneider** [comment]
@stwerner97 What are the endpoint files about exactly? They are configured in the `trace.yml` even for the other networks but only added to the repo for abilene. Do you know?

**Comment by ycfhw1** [comment]
> @stwerner97 What are the endpoint files about exactly? They are configured in the `trace.yml` even for the other networks but only added to the repo for abilene. Do you know?

i know what the endpoints file about，it is used to sample the endpoints to create the request. i thought it was a part of the Specific datasets.without germany50.npy and other endpoints npy,the script.py can't run with other larger network.i have solved the problem already,thank you

**Comment by stefanbschneider** [comment]
Great to hear that you solved the problem already. What did you do exactly to solve it?

**Comment by stweigand97** [comment]
As we had some issues finding suitable (and similar) trace datasets for each scenario, the Abilene data is used in all cases. For network topologies larger than Abilene, we first subsample endpoint nodes and use these as ingress / egress nodes. The arrival rates at these designated nodes then follows the pattern of the Abilene data. 

Hope this helps!

**Comment by ycfhw1** [comment]
> Great to hear that you solved the problem already. What did you do exactly to solve it?

i find the file in another repository,(https://github.com/FreeeBird/Flow-By-Flow-Prediction/tree/main/dataset)  and change the data to make the sum of it to 1 by multiplying a factor.After that the program can run properly.i am not sure whether way is right or not,as i have not done the expriment yet.Can you give me some sugguestions？thanks!

**Comment by ycfhw1** [comment]
> As we had some issues finding suitable (and similar) trace datasets for each scenario, the Abilene data is used in all cases. For network topologies larger than Abilene, we first subsample endpoint nodes and use these as ingress / egress nodes. The arrival rates at these designated nodes then follows the pattern of the Abilene data.
> 
> Hope this helps!

thank you for your help!

**Comment by stweigand97** [comment]
> 
> i find the file in another repository,(https://github.com/FreeeBird/Flow-By-Flow-Prediction/tree/main/dataset) and change the data to make the sum of it to 1 by multiplying a factor.After that the program can run properly.i am not sure whether way is right or not,as i have not done the expriment yet.Can you give me some sugguestions？thanks!

That sounds good to me. In general, the trace should have the shape `[Batch Size, Time Steps, Nodes, Nodes]`, where each entry in the batch dimension is a trace recorded for the time period of e.g. a day.  Each matrix `[Nodes, Nodes]` should contain values that sum to one. Other than that, there should not be any further constraints.
